/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "device_system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(edgez_devices_v1_SystemStatusBatch, edgez_devices_v1_SystemStatusBatch, 4)


PB_BIND(edgez_devices_v1_SystemStatus, edgez_devices_v1_SystemStatus, 2)


PB_BIND(edgez_devices_v1_Topology, edgez_devices_v1_Topology, 2)


PB_BIND(edgez_devices_v1_TopologyLink, edgez_devices_v1_TopologyLink, AUTO)


PB_BIND(edgez_devices_v1_HalowRf, edgez_devices_v1_HalowRf, AUTO)


PB_BIND(edgez_devices_v1_HalowRfLinks, edgez_devices_v1_HalowRfLinks, AUTO)


PB_BIND(edgez_devices_v1_SystemCommand, edgez_devices_v1_SystemCommand, 2)


PB_BIND(edgez_devices_v1_CommandHeader, edgez_devices_v1_CommandHeader, AUTO)


PB_BIND(edgez_devices_v1_OtaCommand, edgez_devices_v1_OtaCommand, 2)
