/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_EDGEZ_DEVICES_V1_DEVICE_SYSTEM_PB_H_INCLUDED
#define PB_EDGEZ_DEVICES_V1_DEVICE_SYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _edgez_devices_v1_DeviceStatus {
    edgez_devices_v1_DeviceStatus_DEVICE_STATUS_UNSPECIFIED = 0,
    edgez_devices_v1_DeviceStatus_DEVICE_STATUS_ONLINE = 1,
    edgez_devices_v1_DeviceStatus_DEVICE_STATUS_OFFLINE = 2
} edgez_devices_v1_DeviceStatus;

typedef enum _edgez_devices_v1_GatewayStatus {
    edgez_devices_v1_GatewayStatus_GATEWAY_STATUS_UNSPECIFIED = 0,
    edgez_devices_v1_GatewayStatus_GATEWAY_STATUS_ONLINE = 1,
    edgez_devices_v1_GatewayStatus_GATEWAY_STATUS_OFFLINE = 2,
    edgez_devices_v1_GatewayStatus_GATEWAY_STATUS_DISABLED = 3
} edgez_devices_v1_GatewayStatus;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) edgez_devices_v1_TopologyLink_peer_halow_mac_t;
typedef struct _edgez_devices_v1_TopologyLink {
    edgez_devices_v1_TopologyLink_peer_halow_mac_t peer_halow_mac;
    uint32_t age_ms;
    bool has_rssi;
    int32_t rssi;
} edgez_devices_v1_TopologyLink;

typedef struct _edgez_devices_v1_Topology {
    pb_size_t links_count;
    edgez_devices_v1_TopologyLink links[16];
} edgez_devices_v1_Topology;

typedef struct _edgez_devices_v1_HalowRfLinks {
    bool has_peer_count;
    uint32_t peer_count;
    bool has_average_signal_dbm;
    int32_t average_signal_dbm;
    bool has_minimum_signal_dbm;
    int32_t minimum_signal_dbm;
    bool has_rx_packets;
    uint64_t rx_packets;
    bool has_tx_packets;
    uint64_t tx_packets;
    bool has_tx_retries;
    uint64_t tx_retries;
    bool has_tx_failed;
    uint64_t tx_failed;
} edgez_devices_v1_HalowRfLinks;

typedef struct _edgez_devices_v1_HalowRf {
    uint32_t version;
    uint64_t observed_at;
    bool radio_enabled;
    bool available;
    bool has_channel;
    uint32_t channel;
    bool has_frequency;
    uint32_t frequency;
    bool has_bandwidth_mhz;
    uint32_t bandwidth_mhz;
    bool has_signal_dbm;
    int32_t signal_dbm;
    bool has_noise_dbm;
    int32_t noise_dbm;
    bool has_quality;
    uint32_t quality;
    bool has_quality_max;
    uint32_t quality_max;
    bool has_links;
    edgez_devices_v1_HalowRfLinks links;
} edgez_devices_v1_HalowRf;

typedef PB_BYTES_ARRAY_T(6) edgez_devices_v1_SystemStatus_halow_mac_t;
typedef struct _edgez_devices_v1_SystemStatus {
    char client_id[128];
    edgez_devices_v1_DeviceStatus status;
    edgez_devices_v1_SystemStatus_halow_mac_t halow_mac;
    char firmware_version[128];
    bool has_topology;
    edgez_devices_v1_Topology topology;
    bool has_halow_rf;
    edgez_devices_v1_HalowRf halow_rf;
    edgez_devices_v1_GatewayStatus gateway_status;
    bool has_wifi_enabled;
    bool wifi_enabled;
} edgez_devices_v1_SystemStatus;

typedef struct _edgez_devices_v1_SystemStatusBatch {
    pb_size_t reports_count;
    edgez_devices_v1_SystemStatus reports[16];
} edgez_devices_v1_SystemStatusBatch;

typedef struct _edgez_devices_v1_CommandHeader {
    uint32_t version;
    char request_id[64];
} edgez_devices_v1_CommandHeader;

typedef struct _edgez_devices_v1_OtaCommand {
    char url[512];
} edgez_devices_v1_OtaCommand;

typedef struct _edgez_devices_v1_SystemCommand {
    bool has_header;
    edgez_devices_v1_CommandHeader header;
    pb_size_t which_command;
    union {
        edgez_devices_v1_OtaCommand ota;
    } command;
} edgez_devices_v1_SystemCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _edgez_devices_v1_DeviceStatus_MIN edgez_devices_v1_DeviceStatus_DEVICE_STATUS_UNSPECIFIED
#define _edgez_devices_v1_DeviceStatus_MAX edgez_devices_v1_DeviceStatus_DEVICE_STATUS_OFFLINE
#define _edgez_devices_v1_DeviceStatus_ARRAYSIZE ((edgez_devices_v1_DeviceStatus)(edgez_devices_v1_DeviceStatus_DEVICE_STATUS_OFFLINE+1))

#define _edgez_devices_v1_GatewayStatus_MIN edgez_devices_v1_GatewayStatus_GATEWAY_STATUS_UNSPECIFIED
#define _edgez_devices_v1_GatewayStatus_MAX edgez_devices_v1_GatewayStatus_GATEWAY_STATUS_DISABLED
#define _edgez_devices_v1_GatewayStatus_ARRAYSIZE ((edgez_devices_v1_GatewayStatus)(edgez_devices_v1_GatewayStatus_GATEWAY_STATUS_DISABLED+1))


#define edgez_devices_v1_SystemStatus_status_ENUMTYPE edgez_devices_v1_DeviceStatus
#define edgez_devices_v1_SystemStatus_gateway_status_ENUMTYPE edgez_devices_v1_GatewayStatus









/* Initializer values for message structs */
#define edgez_devices_v1_SystemStatusBatch_init_default {0, {edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default, edgez_devices_v1_SystemStatus_init_default}}
#define edgez_devices_v1_SystemStatus_init_default {"", _edgez_devices_v1_DeviceStatus_MIN, {0, {0}}, "", false, edgez_devices_v1_Topology_init_default, false, edgez_devices_v1_HalowRf_init_default, _edgez_devices_v1_GatewayStatus_MIN, false, 0}
#define edgez_devices_v1_Topology_init_default   {0, {edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default, edgez_devices_v1_TopologyLink_init_default}}
#define edgez_devices_v1_TopologyLink_init_default {{0, {0}}, 0, false, 0}
#define edgez_devices_v1_HalowRf_init_default    {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, edgez_devices_v1_HalowRfLinks_init_default}
#define edgez_devices_v1_HalowRfLinks_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define edgez_devices_v1_SystemCommand_init_default {false, edgez_devices_v1_CommandHeader_init_default, 0, {edgez_devices_v1_OtaCommand_init_default}}
#define edgez_devices_v1_CommandHeader_init_default {0, ""}
#define edgez_devices_v1_OtaCommand_init_default {""}
#define edgez_devices_v1_SystemStatusBatch_init_zero {0, {edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero, edgez_devices_v1_SystemStatus_init_zero}}
#define edgez_devices_v1_SystemStatus_init_zero  {"", _edgez_devices_v1_DeviceStatus_MIN, {0, {0}}, "", false, edgez_devices_v1_Topology_init_zero, false, edgez_devices_v1_HalowRf_init_zero, _edgez_devices_v1_GatewayStatus_MIN, false, 0}
#define edgez_devices_v1_Topology_init_zero      {0, {edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero, edgez_devices_v1_TopologyLink_init_zero}}
#define edgez_devices_v1_TopologyLink_init_zero  {{0, {0}}, 0, false, 0}
#define edgez_devices_v1_HalowRf_init_zero       {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, edgez_devices_v1_HalowRfLinks_init_zero}
#define edgez_devices_v1_HalowRfLinks_init_zero  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define edgez_devices_v1_SystemCommand_init_zero {false, edgez_devices_v1_CommandHeader_init_zero, 0, {edgez_devices_v1_OtaCommand_init_zero}}
#define edgez_devices_v1_CommandHeader_init_zero {0, ""}
#define edgez_devices_v1_OtaCommand_init_zero    {""}

/* Field tags (for use in manual encoding/decoding) */
#define edgez_devices_v1_TopologyLink_peer_halow_mac_tag 1
#define edgez_devices_v1_TopologyLink_age_ms_tag 2
#define edgez_devices_v1_TopologyLink_rssi_tag   3
#define edgez_devices_v1_Topology_links_tag      1
#define edgez_devices_v1_HalowRfLinks_peer_count_tag 1
#define edgez_devices_v1_HalowRfLinks_average_signal_dbm_tag 2
#define edgez_devices_v1_HalowRfLinks_minimum_signal_dbm_tag 3
#define edgez_devices_v1_HalowRfLinks_rx_packets_tag 4
#define edgez_devices_v1_HalowRfLinks_tx_packets_tag 5
#define edgez_devices_v1_HalowRfLinks_tx_retries_tag 6
#define edgez_devices_v1_HalowRfLinks_tx_failed_tag 7
#define edgez_devices_v1_HalowRf_version_tag     1
#define edgez_devices_v1_HalowRf_observed_at_tag 2
#define edgez_devices_v1_HalowRf_radio_enabled_tag 3
#define edgez_devices_v1_HalowRf_available_tag   4
#define edgez_devices_v1_HalowRf_channel_tag     5
#define edgez_devices_v1_HalowRf_frequency_tag   6
#define edgez_devices_v1_HalowRf_bandwidth_mhz_tag 7
#define edgez_devices_v1_HalowRf_signal_dbm_tag  8
#define edgez_devices_v1_HalowRf_noise_dbm_tag   9
#define edgez_devices_v1_HalowRf_quality_tag     10
#define edgez_devices_v1_HalowRf_quality_max_tag 11
#define edgez_devices_v1_HalowRf_links_tag       12
#define edgez_devices_v1_SystemStatus_client_id_tag 1
#define edgez_devices_v1_SystemStatus_status_tag 2
#define edgez_devices_v1_SystemStatus_halow_mac_tag 3
#define edgez_devices_v1_SystemStatus_firmware_version_tag 4
#define edgez_devices_v1_SystemStatus_topology_tag 5
#define edgez_devices_v1_SystemStatus_halow_rf_tag 6
#define edgez_devices_v1_SystemStatus_gateway_status_tag 7
#define edgez_devices_v1_SystemStatus_wifi_enabled_tag 8
#define edgez_devices_v1_SystemStatusBatch_reports_tag 1
#define edgez_devices_v1_CommandHeader_version_tag 1
#define edgez_devices_v1_CommandHeader_request_id_tag 2
#define edgez_devices_v1_OtaCommand_url_tag      1
#define edgez_devices_v1_SystemCommand_header_tag 1
#define edgez_devices_v1_SystemCommand_ota_tag   10

/* Struct field encoding specification for nanopb */
#define edgez_devices_v1_SystemStatusBatch_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  reports,           1)
#define edgez_devices_v1_SystemStatusBatch_CALLBACK NULL
#define edgez_devices_v1_SystemStatusBatch_DEFAULT NULL
#define edgez_devices_v1_SystemStatusBatch_reports_MSGTYPE edgez_devices_v1_SystemStatus

#define edgez_devices_v1_SystemStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   client_id,         1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   SINGULAR, BYTES,    halow_mac,         3) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  topology,          5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  halow_rf,          6) \
X(a, STATIC,   SINGULAR, UENUM,    gateway_status,    7) \
X(a, STATIC,   OPTIONAL, BOOL,     wifi_enabled,      8)
#define edgez_devices_v1_SystemStatus_CALLBACK NULL
#define edgez_devices_v1_SystemStatus_DEFAULT NULL
#define edgez_devices_v1_SystemStatus_topology_MSGTYPE edgez_devices_v1_Topology
#define edgez_devices_v1_SystemStatus_halow_rf_MSGTYPE edgez_devices_v1_HalowRf

#define edgez_devices_v1_Topology_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  links,             1)
#define edgez_devices_v1_Topology_CALLBACK NULL
#define edgez_devices_v1_Topology_DEFAULT NULL
#define edgez_devices_v1_Topology_links_MSGTYPE edgez_devices_v1_TopologyLink

#define edgez_devices_v1_TopologyLink_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    peer_halow_mac,    1) \
X(a, STATIC,   SINGULAR, UINT32,   age_ms,            2) \
X(a, STATIC,   OPTIONAL, SINT32,   rssi,              3)
#define edgez_devices_v1_TopologyLink_CALLBACK NULL
#define edgez_devices_v1_TopologyLink_DEFAULT NULL

#define edgez_devices_v1_HalowRf_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, STATIC,   SINGULAR, UINT64,   observed_at,       2) \
X(a, STATIC,   SINGULAR, BOOL,     radio_enabled,     3) \
X(a, STATIC,   SINGULAR, BOOL,     available,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   channel,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   frequency,         6) \
X(a, STATIC,   OPTIONAL, UINT32,   bandwidth_mhz,     7) \
X(a, STATIC,   OPTIONAL, SINT32,   signal_dbm,        8) \
X(a, STATIC,   OPTIONAL, SINT32,   noise_dbm,         9) \
X(a, STATIC,   OPTIONAL, UINT32,   quality,          10) \
X(a, STATIC,   OPTIONAL, UINT32,   quality_max,      11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  links,            12)
#define edgez_devices_v1_HalowRf_CALLBACK NULL
#define edgez_devices_v1_HalowRf_DEFAULT NULL
#define edgez_devices_v1_HalowRf_links_MSGTYPE edgez_devices_v1_HalowRfLinks

#define edgez_devices_v1_HalowRfLinks_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   peer_count,        1) \
X(a, STATIC,   OPTIONAL, SINT32,   average_signal_dbm,   2) \
X(a, STATIC,   OPTIONAL, SINT32,   minimum_signal_dbm,   3) \
X(a, STATIC,   OPTIONAL, UINT64,   rx_packets,        4) \
X(a, STATIC,   OPTIONAL, UINT64,   tx_packets,        5) \
X(a, STATIC,   OPTIONAL, UINT64,   tx_retries,        6) \
X(a, STATIC,   OPTIONAL, UINT64,   tx_failed,         7)
#define edgez_devices_v1_HalowRfLinks_CALLBACK NULL
#define edgez_devices_v1_HalowRfLinks_DEFAULT NULL

#define edgez_devices_v1_SystemCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,ota,command.ota),  10)
#define edgez_devices_v1_SystemCommand_CALLBACK NULL
#define edgez_devices_v1_SystemCommand_DEFAULT NULL
#define edgez_devices_v1_SystemCommand_header_MSGTYPE edgez_devices_v1_CommandHeader
#define edgez_devices_v1_SystemCommand_command_ota_MSGTYPE edgez_devices_v1_OtaCommand

#define edgez_devices_v1_CommandHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, STATIC,   SINGULAR, STRING,   request_id,        2)
#define edgez_devices_v1_CommandHeader_CALLBACK NULL
#define edgez_devices_v1_CommandHeader_DEFAULT NULL

#define edgez_devices_v1_OtaCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   url,               1)
#define edgez_devices_v1_OtaCommand_CALLBACK NULL
#define edgez_devices_v1_OtaCommand_DEFAULT NULL

extern const pb_msgdesc_t edgez_devices_v1_SystemStatusBatch_msg;
extern const pb_msgdesc_t edgez_devices_v1_SystemStatus_msg;
extern const pb_msgdesc_t edgez_devices_v1_Topology_msg;
extern const pb_msgdesc_t edgez_devices_v1_TopologyLink_msg;
extern const pb_msgdesc_t edgez_devices_v1_HalowRf_msg;
extern const pb_msgdesc_t edgez_devices_v1_HalowRfLinks_msg;
extern const pb_msgdesc_t edgez_devices_v1_SystemCommand_msg;
extern const pb_msgdesc_t edgez_devices_v1_CommandHeader_msg;
extern const pb_msgdesc_t edgez_devices_v1_OtaCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define edgez_devices_v1_SystemStatusBatch_fields &edgez_devices_v1_SystemStatusBatch_msg
#define edgez_devices_v1_SystemStatus_fields &edgez_devices_v1_SystemStatus_msg
#define edgez_devices_v1_Topology_fields &edgez_devices_v1_Topology_msg
#define edgez_devices_v1_TopologyLink_fields &edgez_devices_v1_TopologyLink_msg
#define edgez_devices_v1_HalowRf_fields &edgez_devices_v1_HalowRf_msg
#define edgez_devices_v1_HalowRfLinks_fields &edgez_devices_v1_HalowRfLinks_msg
#define edgez_devices_v1_SystemCommand_fields &edgez_devices_v1_SystemCommand_msg
#define edgez_devices_v1_CommandHeader_fields &edgez_devices_v1_CommandHeader_msg
#define edgez_devices_v1_OtaCommand_fields &edgez_devices_v1_OtaCommand_msg

/* Maximum encoded size of messages (where known) */
#define EDGEZ_DEVICES_V1_DEVICE_SYSTEM_PB_H_MAX_SIZE edgez_devices_v1_SystemStatusBatch_size
#define edgez_devices_v1_CommandHeader_size      71
#define edgez_devices_v1_HalowRfLinks_size       62
#define edgez_devices_v1_HalowRf_size            127
#define edgez_devices_v1_OtaCommand_size         514
#define edgez_devices_v1_SystemCommand_size      590
#define edgez_devices_v1_SystemStatusBatch_size  12176
#define edgez_devices_v1_SystemStatus_size       758
#define edgez_devices_v1_TopologyLink_size       20
#define edgez_devices_v1_Topology_size           352

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
