/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AI_EDGEZ_HALOW_USB_CONTROL_PB_H_INCLUDED
#define PB_AI_EDGEZ_HALOW_USB_CONTROL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ai_edgez_halow_Operation {
    ai_edgez_halow_Operation_OPERATION_UNSPECIFIED = 0,
    ai_edgez_halow_Operation_REQUEST = 1,
    ai_edgez_halow_Operation_RESPONSE = 2,
    ai_edgez_halow_Operation_ACKNOWLEDGE = 3,
    ai_edgez_halow_Operation_STREAMING = 4,
    ai_edgez_halow_Operation_BROADCAST = 9
} ai_edgez_halow_Operation;

typedef enum _ai_edgez_halow_Interface {
    ai_edgez_halow_Interface_INTERFACE_UNSPECIFIED = 0,
    ai_edgez_halow_Interface_USB = 1,
    ai_edgez_halow_Interface_BLE = 2,
    ai_edgez_halow_Interface_WIFI = 3,
    ai_edgez_halow_Interface_ETHERNET = 4,
    ai_edgez_halow_Interface_HALOW = 5,
    ai_edgez_halow_Interface_LORA = 6,
    ai_edgez_halow_Interface_LIBP2P = 7
} ai_edgez_halow_Interface;

typedef enum _ai_edgez_halow_Mime {
    ai_edgez_halow_Mime_MIME_UNSPECIFIED = 0,
    ai_edgez_halow_Mime_MIME_TEXT = 1,
    ai_edgez_halow_Mime_MIME_VOICE = 2,
    ai_edgez_halow_Mime_MIME_IMAGE = 3,
    ai_edgez_halow_Mime_MIME_VIDEO = 4,
    ai_edgez_halow_Mime_MIME_BINARY = 5,
    ai_edgez_halow_Mime_MIME_VOICE_CALL = 6 /* realtime EVC2 binary call frame; best effort, not persisted */
} ai_edgez_halow_Mime;

typedef enum _ai_edgez_halow_MarkerColor {
    ai_edgez_halow_MarkerColor_MARKER_DEFAULT = 0,
    ai_edgez_halow_MarkerColor_MARKER_RED = 1,
    ai_edgez_halow_MarkerColor_MARKER_BLUE = 2,
    ai_edgez_halow_MarkerColor_MARKER_PURPLE = 3,
    ai_edgez_halow_MarkerColor_MARKER_YELLOW = 4,
    ai_edgez_halow_MarkerColor_MARKER_PINK = 5,
    ai_edgez_halow_MarkerColor_MARKER_BROWN = 6,
    ai_edgez_halow_MarkerColor_MARKER_GREEN = 7,
    ai_edgez_halow_MarkerColor_MARKER_ORANGE = 8,
    ai_edgez_halow_MarkerColor_MARKER_DEEP_PURPLE = 9,
    ai_edgez_halow_MarkerColor_MARKER_LIGHT_BLUE = 10,
    ai_edgez_halow_MarkerColor_MARKER_CYAN = 11,
    ai_edgez_halow_MarkerColor_MARKER_TEAL = 12,
    ai_edgez_halow_MarkerColor_MARKER_LIME = 13,
    ai_edgez_halow_MarkerColor_MARKER_DEEP_ORANGE = 14,
    ai_edgez_halow_MarkerColor_MARKER_GRAY = 15,
    ai_edgez_halow_MarkerColor_MARKER_BLUE_GRAY = 16
} ai_edgez_halow_MarkerColor;

typedef enum _ai_edgez_halow_DeviceSettingsAction {
    ai_edgez_halow_DeviceSettingsAction_DEVICE_SETTINGS_ACTION_UNSPECIFIED = 0,
    ai_edgez_halow_DeviceSettingsAction_DEVICE_SETTINGS_GET = 1,
    ai_edgez_halow_DeviceSettingsAction_DEVICE_SETTINGS_SET = 2,
    ai_edgez_halow_DeviceSettingsAction_DEVICE_SETTINGS_REPORT = 3
} ai_edgez_halow_DeviceSettingsAction;

typedef enum _ai_edgez_halow_ScriptConfigAction {
    ai_edgez_halow_ScriptConfigAction_SCRIPT_CONFIG_ACTION_UNSPECIFIED = 0,
    ai_edgez_halow_ScriptConfigAction_SCRIPT_CONFIG_BEGIN = 1,
    ai_edgez_halow_ScriptConfigAction_SCRIPT_CONFIG_CHUNK = 2,
    ai_edgez_halow_ScriptConfigAction_SCRIPT_CONFIG_COMMIT = 3,
    ai_edgez_halow_ScriptConfigAction_SCRIPT_CONFIG_DELETE = 4,
    ai_edgez_halow_ScriptConfigAction_SCRIPT_CONFIG_REPORT = 5
} ai_edgez_halow_ScriptConfigAction;

typedef enum _ai_edgez_halow_LicenseStatus {
    ai_edgez_halow_LicenseStatus_LICENSE_STATUS_UNSPECIFIED = 0,
    ai_edgez_halow_LicenseStatus_LICENSE_STATUS_AUTHORIZED = 1,
    ai_edgez_halow_LicenseStatus_LICENSE_STATUS_DEVICE_NOT_LICENSED = 2,
    ai_edgez_halow_LicenseStatus_LICENSE_STATUS_SDK_RELEASE_REQUIRED = 3,
    ai_edgez_halow_LicenseStatus_LICENSE_STATUS_SDK_VERSION_INCOMPATIBLE = 4,
    ai_edgez_halow_LicenseStatus_LICENSE_STATUS_SDK_RELEASE_INVALID = 5
} ai_edgez_halow_LicenseStatus;

typedef enum _ai_edgez_halow_DeviceType {
    ai_edgez_halow_DeviceType_DEVICE_TYPE_UNSPECIFIED = 0,
    ai_edgez_halow_DeviceType_DEVICE_TYPE_UNKNOWN = 1,
    ai_edgez_halow_DeviceType_DEVICE_TYPE_USER = 2,
    ai_edgez_halow_DeviceType_DEVICE_TYPE_GATEWAY = 3,
    ai_edgez_halow_DeviceType_DEVICE_TYPE_BEACON = 4,
    ai_edgez_halow_DeviceType_DEVICE_TYPE_SENSOR = 5,
    ai_edgez_halow_DeviceType_DEVICE_TYPE_RELAY = 6
} ai_edgez_halow_DeviceType;

typedef enum _ai_edgez_halow_AlertCondition {
    ai_edgez_halow_AlertCondition_ALERT_CONDITION_UNSPECIFIED = 0,
    ai_edgez_halow_AlertCondition_ALERT_CONDITION_ENTER = 1,
    ai_edgez_halow_AlertCondition_ALERT_CONDITION_EXIT = 2,
    ai_edgez_halow_AlertCondition_ALERT_CONDITION_NEAR = 3,
    ai_edgez_halow_AlertCondition_ALERT_CONDITION_FAR = 4,
    ai_edgez_halow_AlertCondition_ALERT_CONDITION_LOW_BATTERY = 5
} ai_edgez_halow_AlertCondition;

typedef enum _ai_edgez_halow_SensorType {
    ai_edgez_halow_SensorType_SENSOR_UNKNOWN = 0,
    ai_edgez_halow_SensorType_SENSOR_TEMPERATURE = 1,
    ai_edgez_halow_SensorType_SENSOR_HUMIDITY = 2,
    ai_edgez_halow_SensorType_SENSOR_LATITUDE = 3,
    ai_edgez_halow_SensorType_SENSOR_LONGITUDE = 4,
    ai_edgez_halow_SensorType_SENSOR_LENGTH = 5,
    ai_edgez_halow_SensorType_SENSOR_ACCEL_X = 6, /* acceleration in m/s^2 */
    ai_edgez_halow_SensorType_SENSOR_ACCEL_Y = 7, /* acceleration in m/s^2 */
    ai_edgez_halow_SensorType_SENSOR_ACCEL_Z = 8, /* acceleration in m/s^2 */
    ai_edgez_halow_SensorType_SENSOR_GYRO_X = 9, /* angular velocity in rad/s */
    ai_edgez_halow_SensorType_SENSOR_GYRO_Y = 10, /* angular velocity in rad/s */
    ai_edgez_halow_SensorType_SENSOR_GYRO_Z = 11 /* angular velocity in rad/s */
} ai_edgez_halow_SensorType;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(420) ai_edgez_halow_MessageBody_payload_t;
typedef struct _ai_edgez_halow_MessageBody {
    uint64_t message_id_high; /* high 64 bits of message UUID */
    uint64_t message_id_low; /* low 64 bits of message UUID */
    int32_t sequence; /* when a message need to split into chunks, use sequence to control it */
    ai_edgez_halow_Mime mime; /* encrypted payload media type */
    ai_edgez_halow_MessageBody_payload_t payload;
    uint64_t group_id_high; /* omitted for direct messages */
    uint64_t group_id_low; /* omitted for direct messages */
} ai_edgez_halow_MessageBody;

typedef struct _ai_edgez_halow_GeoFence {
    uint64_t id_high;
    uint64_t id_low;
    char name[65];
    ai_edgez_halow_MarkerColor marker;
    ai_edgez_halow_AlertCondition alert_condition;
    uint32_t geo_index;
} ai_edgez_halow_GeoFence;

typedef struct _ai_edgez_halow_SensorData {
    ai_edgez_halow_SensorType type;
    pb_size_t which_value;
    union {
        bool bool_value;
        int32_t int_value;
        float float_value;
    } value;
} ai_edgez_halow_SensorData;

typedef struct _ai_edgez_halow_Peer {
    uint64_t id;
    int32_t rssi;
    pb_size_t sensor_data_count;
    ai_edgez_halow_SensorData sensor_data[7];
} ai_edgez_halow_Peer;

typedef struct _ai_edgez_halow_Report {
    pb_size_t peers_count;
    ai_edgez_halow_Peer peers[6];
} ai_edgez_halow_Report;

typedef PB_BYTES_ARRAY_T(32) ai_edgez_halow_Beacon_user_public_key_t;
typedef struct _ai_edgez_halow_Beacon {
    uint64_t user_id_high;
    uint64_t user_id_low;
    char user_name[65];
    ai_edgez_halow_Beacon_user_public_key_t user_public_key;
    float latitude;
    float longitude;
    ai_edgez_halow_MarkerColor marker;
    ai_edgez_halow_DeviceType device_type;
    uint32_t channel_number; /* country-specific S1G receive channel */
    bool sleeping;
    bool has_geo_fence;
    ai_edgez_halow_GeoFence geo_fence;
    pb_size_t sensor_data_count;
    ai_edgez_halow_SensorData sensor_data[7]; /* only for beacon and sensor type */
} ai_edgez_halow_Beacon;

typedef struct _ai_edgez_halow_HaLowInterfaceStatus {
    bool supported;
    bool stack_initialized;
    bool mesh_mode;
    bool link_up;
    bool route_ready;
    bool ready_for_report;
    uint32_t ethertype;
    char mesh_id[33];
    char ip_addr[16];
    char gateway[16];
    uint64_t mac_address;
    ai_edgez_halow_LicenseStatus license_status;
    char firmware_version[33];
} ai_edgez_halow_HaLowInterfaceStatus;

typedef PB_BYTES_ARRAY_T(32) ai_edgez_halow_HaLowInitConfig_user_public_key_t;
typedef struct _ai_edgez_halow_HaLowInitConfig {
    char country_code[3];
    char mesh_id[33];
    char passphrase[65];
    uint32_t max_hop;
    uint64_t user_id_high;
    uint64_t user_id_low;
    char user_name[65];
    ai_edgez_halow_HaLowInitConfig_user_public_key_t user_public_key;
    char marker[17];
    bool has_location;
    float latitude;
    float longitude;
    uint32_t mesh_bandwidth_mhz;
    uint32_t mesh_frequency_khz;
} ai_edgez_halow_HaLowInitConfig;

typedef PB_BYTES_ARRAY_T(32) ai_edgez_halow_DeviceSettings_user_public_key_t;
typedef PB_BYTES_ARRAY_T(32) ai_edgez_halow_DeviceSettings_user_private_key_t;
typedef struct _ai_edgez_halow_DeviceSettings {
    ai_edgez_halow_DeviceSettingsAction action;
    /* Legacy device/relay flag. New clients use device_type instead. */
    bool device_mode_enabled;
    char mesh_id[33];
    bool share_location;
    char user_name[65];
    ai_edgez_halow_MarkerColor marker;
    uint32_t beacon_interval_seconds;
    uint64_t user_id_high;
    uint64_t user_id_low;
    ai_edgez_halow_DeviceSettings_user_public_key_t user_public_key;
    ai_edgez_halow_DeviceSettings_user_private_key_t user_private_key;
    float latitude;
    float longitude;
    uint32_t max_hop;
    bool has_geo_fence;
    ai_edgez_halow_GeoFence geo_fence;
    char uart_i2c_sensor_type[33];
    char rs485_sensor_type[33];
    uint32_t geo_index;
    char passphrase[65];
    char upstream_wifi_ssid[33];
    char upstream_wifi_passphrase[65];
    uint64_t beacon_unicast;
    ai_edgez_halow_DeviceType device_type;
    bool sleep_mode_enabled;
    uint32_t mesh_frequency_khz;
    uint32_t mesh_bandwidth_mhz;
    bool device_gps_enabled;
} ai_edgez_halow_DeviceSettings;

typedef PB_BYTES_ARRAY_T(220) ai_edgez_halow_ScriptConfig_chunk_t;
typedef struct _ai_edgez_halow_ScriptConfig {
    ai_edgez_halow_ScriptConfigAction action;
    uint32_t script_id;
    char name[65];
    uint32_t version;
    uint32_t total_size;
    uint32_t offset;
    ai_edgez_halow_ScriptConfig_chunk_t chunk;
    char sensor_type[33];
    bool select_uart_i2c;
    bool select_rs485;
    uint32_t global_buffer_size;
    char mime_type[65];
} ai_edgez_halow_ScriptConfig;

typedef PB_BYTES_ARRAY_T(440) ai_edgez_halow_NetworkPacket_payload_t;
typedef struct _ai_edgez_halow_NetworkPacket {
    uint64_t from;
    uint64_t to;
    ai_edgez_halow_Operation operation;
    ai_edgez_halow_Interface interface; /* self interface when option is request,broadcast, target interface for response. */
    pb_size_t which_body;
    union {
        ai_edgez_halow_NetworkPacket_payload_t payload;
        ai_edgez_halow_MessageBody msg;
        ai_edgez_halow_HaLowInterfaceStatus status;
        ai_edgez_halow_HaLowInitConfig init;
        ai_edgez_halow_DeviceSettings device_settings;
        ai_edgez_halow_ScriptConfig script_config;
        ai_edgez_halow_Beacon beacon; /* beacon heard from the management Vendor IE */
        ai_edgez_halow_Report report;
    } body;
} ai_edgez_halow_NetworkPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ai_edgez_halow_Operation_MIN ai_edgez_halow_Operation_OPERATION_UNSPECIFIED
#define _ai_edgez_halow_Operation_MAX ai_edgez_halow_Operation_BROADCAST
#define _ai_edgez_halow_Operation_ARRAYSIZE ((ai_edgez_halow_Operation)(ai_edgez_halow_Operation_BROADCAST+1))

#define _ai_edgez_halow_Interface_MIN ai_edgez_halow_Interface_INTERFACE_UNSPECIFIED
#define _ai_edgez_halow_Interface_MAX ai_edgez_halow_Interface_LIBP2P
#define _ai_edgez_halow_Interface_ARRAYSIZE ((ai_edgez_halow_Interface)(ai_edgez_halow_Interface_LIBP2P+1))

#define _ai_edgez_halow_Mime_MIN ai_edgez_halow_Mime_MIME_UNSPECIFIED
#define _ai_edgez_halow_Mime_MAX ai_edgez_halow_Mime_MIME_VOICE_CALL
#define _ai_edgez_halow_Mime_ARRAYSIZE ((ai_edgez_halow_Mime)(ai_edgez_halow_Mime_MIME_VOICE_CALL+1))

#define _ai_edgez_halow_MarkerColor_MIN ai_edgez_halow_MarkerColor_MARKER_DEFAULT
#define _ai_edgez_halow_MarkerColor_MAX ai_edgez_halow_MarkerColor_MARKER_BLUE_GRAY
#define _ai_edgez_halow_MarkerColor_ARRAYSIZE ((ai_edgez_halow_MarkerColor)(ai_edgez_halow_MarkerColor_MARKER_BLUE_GRAY+1))

#define _ai_edgez_halow_DeviceSettingsAction_MIN ai_edgez_halow_DeviceSettingsAction_DEVICE_SETTINGS_ACTION_UNSPECIFIED
#define _ai_edgez_halow_DeviceSettingsAction_MAX ai_edgez_halow_DeviceSettingsAction_DEVICE_SETTINGS_REPORT
#define _ai_edgez_halow_DeviceSettingsAction_ARRAYSIZE ((ai_edgez_halow_DeviceSettingsAction)(ai_edgez_halow_DeviceSettingsAction_DEVICE_SETTINGS_REPORT+1))

#define _ai_edgez_halow_ScriptConfigAction_MIN ai_edgez_halow_ScriptConfigAction_SCRIPT_CONFIG_ACTION_UNSPECIFIED
#define _ai_edgez_halow_ScriptConfigAction_MAX ai_edgez_halow_ScriptConfigAction_SCRIPT_CONFIG_REPORT
#define _ai_edgez_halow_ScriptConfigAction_ARRAYSIZE ((ai_edgez_halow_ScriptConfigAction)(ai_edgez_halow_ScriptConfigAction_SCRIPT_CONFIG_REPORT+1))

#define _ai_edgez_halow_LicenseStatus_MIN ai_edgez_halow_LicenseStatus_LICENSE_STATUS_UNSPECIFIED
#define _ai_edgez_halow_LicenseStatus_MAX ai_edgez_halow_LicenseStatus_LICENSE_STATUS_SDK_RELEASE_INVALID
#define _ai_edgez_halow_LicenseStatus_ARRAYSIZE ((ai_edgez_halow_LicenseStatus)(ai_edgez_halow_LicenseStatus_LICENSE_STATUS_SDK_RELEASE_INVALID+1))

#define _ai_edgez_halow_DeviceType_MIN ai_edgez_halow_DeviceType_DEVICE_TYPE_UNSPECIFIED
#define _ai_edgez_halow_DeviceType_MAX ai_edgez_halow_DeviceType_DEVICE_TYPE_RELAY
#define _ai_edgez_halow_DeviceType_ARRAYSIZE ((ai_edgez_halow_DeviceType)(ai_edgez_halow_DeviceType_DEVICE_TYPE_RELAY+1))

#define _ai_edgez_halow_AlertCondition_MIN ai_edgez_halow_AlertCondition_ALERT_CONDITION_UNSPECIFIED
#define _ai_edgez_halow_AlertCondition_MAX ai_edgez_halow_AlertCondition_ALERT_CONDITION_LOW_BATTERY
#define _ai_edgez_halow_AlertCondition_ARRAYSIZE ((ai_edgez_halow_AlertCondition)(ai_edgez_halow_AlertCondition_ALERT_CONDITION_LOW_BATTERY+1))

#define _ai_edgez_halow_SensorType_MIN ai_edgez_halow_SensorType_SENSOR_UNKNOWN
#define _ai_edgez_halow_SensorType_MAX ai_edgez_halow_SensorType_SENSOR_GYRO_Z
#define _ai_edgez_halow_SensorType_ARRAYSIZE ((ai_edgez_halow_SensorType)(ai_edgez_halow_SensorType_SENSOR_GYRO_Z+1))

#define ai_edgez_halow_MessageBody_mime_ENUMTYPE ai_edgez_halow_Mime


#define ai_edgez_halow_NetworkPacket_operation_ENUMTYPE ai_edgez_halow_Operation
#define ai_edgez_halow_NetworkPacket_interface_ENUMTYPE ai_edgez_halow_Interface

#define ai_edgez_halow_GeoFence_marker_ENUMTYPE ai_edgez_halow_MarkerColor
#define ai_edgez_halow_GeoFence_alert_condition_ENUMTYPE ai_edgez_halow_AlertCondition

#define ai_edgez_halow_SensorData_type_ENUMTYPE ai_edgez_halow_SensorType


#define ai_edgez_halow_Beacon_marker_ENUMTYPE ai_edgez_halow_MarkerColor
#define ai_edgez_halow_Beacon_device_type_ENUMTYPE ai_edgez_halow_DeviceType

#define ai_edgez_halow_HaLowInterfaceStatus_license_status_ENUMTYPE ai_edgez_halow_LicenseStatus


#define ai_edgez_halow_DeviceSettings_action_ENUMTYPE ai_edgez_halow_DeviceSettingsAction
#define ai_edgez_halow_DeviceSettings_marker_ENUMTYPE ai_edgez_halow_MarkerColor
#define ai_edgez_halow_DeviceSettings_device_type_ENUMTYPE ai_edgez_halow_DeviceType

#define ai_edgez_halow_ScriptConfig_action_ENUMTYPE ai_edgez_halow_ScriptConfigAction


/* Initializer values for message structs */
#define ai_edgez_halow_MessageBody_init_default  {0, 0, 0, _ai_edgez_halow_Mime_MIN, {0, {0}}, 0, 0}
#define ai_edgez_halow_Report_init_default       {0, {ai_edgez_halow_Peer_init_default, ai_edgez_halow_Peer_init_default, ai_edgez_halow_Peer_init_default, ai_edgez_halow_Peer_init_default, ai_edgez_halow_Peer_init_default, ai_edgez_halow_Peer_init_default}}
#define ai_edgez_halow_NetworkPacket_init_default {0, 0, _ai_edgez_halow_Operation_MIN, _ai_edgez_halow_Interface_MIN, 0, {{0, {0}}}}
#define ai_edgez_halow_GeoFence_init_default     {0, 0, "", _ai_edgez_halow_MarkerColor_MIN, _ai_edgez_halow_AlertCondition_MIN, 0}
#define ai_edgez_halow_SensorData_init_default   {_ai_edgez_halow_SensorType_MIN, 0, {0}}
#define ai_edgez_halow_Peer_init_default         {0, 0, 0, {ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default}}
#define ai_edgez_halow_Beacon_init_default       {0, 0, "", {0, {0}}, 0, 0, _ai_edgez_halow_MarkerColor_MIN, _ai_edgez_halow_DeviceType_MIN, 0, 0, false, ai_edgez_halow_GeoFence_init_default, 0, {ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default, ai_edgez_halow_SensorData_init_default}}
#define ai_edgez_halow_HaLowInterfaceStatus_init_default {0, 0, 0, 0, 0, 0, 0, "", "", "", 0, _ai_edgez_halow_LicenseStatus_MIN, ""}
#define ai_edgez_halow_HaLowInitConfig_init_default {"", "", "", 0, 0, 0, "", {0, {0}}, "", 0, 0, 0, 0, 0}
#define ai_edgez_halow_DeviceSettings_init_default {_ai_edgez_halow_DeviceSettingsAction_MIN, 0, "", 0, "", _ai_edgez_halow_MarkerColor_MIN, 0, 0, 0, {0, {0}}, {0, {0}}, 0, 0, 0, false, ai_edgez_halow_GeoFence_init_default, "", "", 0, "", "", "", 0, _ai_edgez_halow_DeviceType_MIN, 0, 0, 0, 0}
#define ai_edgez_halow_ScriptConfig_init_default {_ai_edgez_halow_ScriptConfigAction_MIN, 0, "", 0, 0, 0, {0, {0}}, "", 0, 0, 0, ""}
#define ai_edgez_halow_MessageBody_init_zero     {0, 0, 0, _ai_edgez_halow_Mime_MIN, {0, {0}}, 0, 0}
#define ai_edgez_halow_Report_init_zero          {0, {ai_edgez_halow_Peer_init_zero, ai_edgez_halow_Peer_init_zero, ai_edgez_halow_Peer_init_zero, ai_edgez_halow_Peer_init_zero, ai_edgez_halow_Peer_init_zero, ai_edgez_halow_Peer_init_zero}}
#define ai_edgez_halow_NetworkPacket_init_zero   {0, 0, _ai_edgez_halow_Operation_MIN, _ai_edgez_halow_Interface_MIN, 0, {{0, {0}}}}
#define ai_edgez_halow_GeoFence_init_zero        {0, 0, "", _ai_edgez_halow_MarkerColor_MIN, _ai_edgez_halow_AlertCondition_MIN, 0}
#define ai_edgez_halow_SensorData_init_zero      {_ai_edgez_halow_SensorType_MIN, 0, {0}}
#define ai_edgez_halow_Peer_init_zero            {0, 0, 0, {ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero}}
#define ai_edgez_halow_Beacon_init_zero          {0, 0, "", {0, {0}}, 0, 0, _ai_edgez_halow_MarkerColor_MIN, _ai_edgez_halow_DeviceType_MIN, 0, 0, false, ai_edgez_halow_GeoFence_init_zero, 0, {ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero, ai_edgez_halow_SensorData_init_zero}}
#define ai_edgez_halow_HaLowInterfaceStatus_init_zero {0, 0, 0, 0, 0, 0, 0, "", "", "", 0, _ai_edgez_halow_LicenseStatus_MIN, ""}
#define ai_edgez_halow_HaLowInitConfig_init_zero {"", "", "", 0, 0, 0, "", {0, {0}}, "", 0, 0, 0, 0, 0}
#define ai_edgez_halow_DeviceSettings_init_zero  {_ai_edgez_halow_DeviceSettingsAction_MIN, 0, "", 0, "", _ai_edgez_halow_MarkerColor_MIN, 0, 0, 0, {0, {0}}, {0, {0}}, 0, 0, 0, false, ai_edgez_halow_GeoFence_init_zero, "", "", 0, "", "", "", 0, _ai_edgez_halow_DeviceType_MIN, 0, 0, 0, 0}
#define ai_edgez_halow_ScriptConfig_init_zero    {_ai_edgez_halow_ScriptConfigAction_MIN, 0, "", 0, 0, 0, {0, {0}}, "", 0, 0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define ai_edgez_halow_MessageBody_message_id_high_tag 1
#define ai_edgez_halow_MessageBody_message_id_low_tag 2
#define ai_edgez_halow_MessageBody_sequence_tag  3
#define ai_edgez_halow_MessageBody_mime_tag      4
#define ai_edgez_halow_MessageBody_payload_tag   5
#define ai_edgez_halow_MessageBody_group_id_high_tag 6
#define ai_edgez_halow_MessageBody_group_id_low_tag 7
#define ai_edgez_halow_GeoFence_id_high_tag      1
#define ai_edgez_halow_GeoFence_id_low_tag       2
#define ai_edgez_halow_GeoFence_name_tag         3
#define ai_edgez_halow_GeoFence_marker_tag       4
#define ai_edgez_halow_GeoFence_alert_condition_tag 5
#define ai_edgez_halow_GeoFence_geo_index_tag    6
#define ai_edgez_halow_SensorData_type_tag       1
#define ai_edgez_halow_SensorData_bool_value_tag 2
#define ai_edgez_halow_SensorData_int_value_tag  3
#define ai_edgez_halow_SensorData_float_value_tag 4
#define ai_edgez_halow_Peer_id_tag               1
#define ai_edgez_halow_Peer_rssi_tag             2
#define ai_edgez_halow_Peer_sensor_data_tag      3
#define ai_edgez_halow_Report_peers_tag          1
#define ai_edgez_halow_Beacon_user_id_high_tag   1
#define ai_edgez_halow_Beacon_user_id_low_tag    2
#define ai_edgez_halow_Beacon_user_name_tag      3
#define ai_edgez_halow_Beacon_user_public_key_tag 4
#define ai_edgez_halow_Beacon_latitude_tag       5
#define ai_edgez_halow_Beacon_longitude_tag      6
#define ai_edgez_halow_Beacon_marker_tag         7
#define ai_edgez_halow_Beacon_device_type_tag    8
#define ai_edgez_halow_Beacon_channel_number_tag 9
#define ai_edgez_halow_Beacon_sleeping_tag       10
#define ai_edgez_halow_Beacon_geo_fence_tag      100
#define ai_edgez_halow_Beacon_sensor_data_tag    101
#define ai_edgez_halow_HaLowInterfaceStatus_supported_tag 1
#define ai_edgez_halow_HaLowInterfaceStatus_stack_initialized_tag 2
#define ai_edgez_halow_HaLowInterfaceStatus_mesh_mode_tag 3
#define ai_edgez_halow_HaLowInterfaceStatus_link_up_tag 4
#define ai_edgez_halow_HaLowInterfaceStatus_route_ready_tag 5
#define ai_edgez_halow_HaLowInterfaceStatus_ready_for_report_tag 6
#define ai_edgez_halow_HaLowInterfaceStatus_ethertype_tag 7
#define ai_edgez_halow_HaLowInterfaceStatus_mesh_id_tag 8
#define ai_edgez_halow_HaLowInterfaceStatus_ip_addr_tag 9
#define ai_edgez_halow_HaLowInterfaceStatus_gateway_tag 10
#define ai_edgez_halow_HaLowInterfaceStatus_mac_address_tag 11
#define ai_edgez_halow_HaLowInterfaceStatus_license_status_tag 12
#define ai_edgez_halow_HaLowInterfaceStatus_firmware_version_tag 13
#define ai_edgez_halow_HaLowInitConfig_country_code_tag 1
#define ai_edgez_halow_HaLowInitConfig_mesh_id_tag 2
#define ai_edgez_halow_HaLowInitConfig_passphrase_tag 3
#define ai_edgez_halow_HaLowInitConfig_max_hop_tag 4
#define ai_edgez_halow_HaLowInitConfig_user_id_high_tag 5
#define ai_edgez_halow_HaLowInitConfig_user_id_low_tag 6
#define ai_edgez_halow_HaLowInitConfig_user_name_tag 7
#define ai_edgez_halow_HaLowInitConfig_user_public_key_tag 8
#define ai_edgez_halow_HaLowInitConfig_marker_tag 9
#define ai_edgez_halow_HaLowInitConfig_has_location_tag 10
#define ai_edgez_halow_HaLowInitConfig_latitude_tag 11
#define ai_edgez_halow_HaLowInitConfig_longitude_tag 12
#define ai_edgez_halow_HaLowInitConfig_mesh_bandwidth_mhz_tag 13
#define ai_edgez_halow_HaLowInitConfig_mesh_frequency_khz_tag 14
#define ai_edgez_halow_DeviceSettings_action_tag 1
#define ai_edgez_halow_DeviceSettings_device_mode_enabled_tag 2
#define ai_edgez_halow_DeviceSettings_mesh_id_tag 3
#define ai_edgez_halow_DeviceSettings_share_location_tag 4
#define ai_edgez_halow_DeviceSettings_user_name_tag 5
#define ai_edgez_halow_DeviceSettings_marker_tag 6
#define ai_edgez_halow_DeviceSettings_beacon_interval_seconds_tag 7
#define ai_edgez_halow_DeviceSettings_user_id_high_tag 8
#define ai_edgez_halow_DeviceSettings_user_id_low_tag 9
#define ai_edgez_halow_DeviceSettings_user_public_key_tag 10
#define ai_edgez_halow_DeviceSettings_user_private_key_tag 11
#define ai_edgez_halow_DeviceSettings_latitude_tag 12
#define ai_edgez_halow_DeviceSettings_longitude_tag 13
#define ai_edgez_halow_DeviceSettings_max_hop_tag 14
#define ai_edgez_halow_DeviceSettings_geo_fence_tag 15
#define ai_edgez_halow_DeviceSettings_uart_i2c_sensor_type_tag 16
#define ai_edgez_halow_DeviceSettings_rs485_sensor_type_tag 17
#define ai_edgez_halow_DeviceSettings_geo_index_tag 18
#define ai_edgez_halow_DeviceSettings_passphrase_tag 19
#define ai_edgez_halow_DeviceSettings_upstream_wifi_ssid_tag 20
#define ai_edgez_halow_DeviceSettings_upstream_wifi_passphrase_tag 21
#define ai_edgez_halow_DeviceSettings_beacon_unicast_tag 22
#define ai_edgez_halow_DeviceSettings_device_type_tag 24
#define ai_edgez_halow_DeviceSettings_sleep_mode_enabled_tag 25
#define ai_edgez_halow_DeviceSettings_mesh_frequency_khz_tag 26
#define ai_edgez_halow_DeviceSettings_mesh_bandwidth_mhz_tag 27
#define ai_edgez_halow_DeviceSettings_device_gps_enabled_tag 28
#define ai_edgez_halow_ScriptConfig_action_tag   1
#define ai_edgez_halow_ScriptConfig_script_id_tag 2
#define ai_edgez_halow_ScriptConfig_name_tag     3
#define ai_edgez_halow_ScriptConfig_version_tag  4
#define ai_edgez_halow_ScriptConfig_total_size_tag 5
#define ai_edgez_halow_ScriptConfig_offset_tag   6
#define ai_edgez_halow_ScriptConfig_chunk_tag    7
#define ai_edgez_halow_ScriptConfig_sensor_type_tag 8
#define ai_edgez_halow_ScriptConfig_select_uart_i2c_tag 9
#define ai_edgez_halow_ScriptConfig_select_rs485_tag 10
#define ai_edgez_halow_ScriptConfig_global_buffer_size_tag 11
#define ai_edgez_halow_ScriptConfig_mime_type_tag 12
#define ai_edgez_halow_NetworkPacket_from_tag    1
#define ai_edgez_halow_NetworkPacket_to_tag      2
#define ai_edgez_halow_NetworkPacket_operation_tag 3
#define ai_edgez_halow_NetworkPacket_interface_tag 4
#define ai_edgez_halow_NetworkPacket_payload_tag 100
#define ai_edgez_halow_NetworkPacket_msg_tag     101
#define ai_edgez_halow_NetworkPacket_status_tag  102
#define ai_edgez_halow_NetworkPacket_init_tag    103
#define ai_edgez_halow_NetworkPacket_device_settings_tag 104
#define ai_edgez_halow_NetworkPacket_script_config_tag 105
#define ai_edgez_halow_NetworkPacket_beacon_tag  106
#define ai_edgez_halow_NetworkPacket_report_tag  107

/* Struct field encoding specification for nanopb */
#define ai_edgez_halow_MessageBody_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   message_id_high,   1) \
X(a, STATIC,   SINGULAR, UINT64,   message_id_low,    2) \
X(a, STATIC,   SINGULAR, SINT32,   sequence,          3) \
X(a, STATIC,   SINGULAR, UENUM,    mime,              4) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           5) \
X(a, STATIC,   SINGULAR, UINT64,   group_id_high,     6) \
X(a, STATIC,   SINGULAR, UINT64,   group_id_low,      7)
#define ai_edgez_halow_MessageBody_CALLBACK NULL
#define ai_edgez_halow_MessageBody_DEFAULT NULL

#define ai_edgez_halow_Report_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  peers,             1)
#define ai_edgez_halow_Report_CALLBACK NULL
#define ai_edgez_halow_Report_DEFAULT NULL
#define ai_edgez_halow_Report_peers_MSGTYPE ai_edgez_halow_Peer

#define ai_edgez_halow_NetworkPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   from,              1) \
X(a, STATIC,   SINGULAR, UINT64,   to,                2) \
X(a, STATIC,   SINGULAR, UENUM,    operation,         3) \
X(a, STATIC,   SINGULAR, UENUM,    interface,         4) \
X(a, STATIC,   ONEOF,    BYTES,    (body,payload,body.payload), 100) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,msg,body.msg), 101) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,status,body.status), 102) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,init,body.init), 103) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,device_settings,body.device_settings), 104) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,script_config,body.script_config), 105) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,beacon,body.beacon), 106) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,report,body.report), 107)
#define ai_edgez_halow_NetworkPacket_CALLBACK NULL
#define ai_edgez_halow_NetworkPacket_DEFAULT NULL
#define ai_edgez_halow_NetworkPacket_body_msg_MSGTYPE ai_edgez_halow_MessageBody
#define ai_edgez_halow_NetworkPacket_body_status_MSGTYPE ai_edgez_halow_HaLowInterfaceStatus
#define ai_edgez_halow_NetworkPacket_body_init_MSGTYPE ai_edgez_halow_HaLowInitConfig
#define ai_edgez_halow_NetworkPacket_body_device_settings_MSGTYPE ai_edgez_halow_DeviceSettings
#define ai_edgez_halow_NetworkPacket_body_script_config_MSGTYPE ai_edgez_halow_ScriptConfig
#define ai_edgez_halow_NetworkPacket_body_beacon_MSGTYPE ai_edgez_halow_Beacon
#define ai_edgez_halow_NetworkPacket_body_report_MSGTYPE ai_edgez_halow_Report

#define ai_edgez_halow_GeoFence_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id_high,           1) \
X(a, STATIC,   SINGULAR, UINT64,   id_low,            2) \
X(a, STATIC,   SINGULAR, STRING,   name,              3) \
X(a, STATIC,   SINGULAR, UENUM,    marker,            4) \
X(a, STATIC,   SINGULAR, UENUM,    alert_condition,   5) \
X(a, STATIC,   SINGULAR, UINT32,   geo_index,         6)
#define ai_edgez_halow_GeoFence_CALLBACK NULL
#define ai_edgez_halow_GeoFence_DEFAULT NULL

#define ai_edgez_halow_SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   2) \
X(a, STATIC,   ONEOF,    SINT32,   (value,int_value,value.int_value),   3) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),   4)
#define ai_edgez_halow_SensorData_CALLBACK NULL
#define ai_edgez_halow_SensorData_DEFAULT NULL

#define ai_edgez_halow_Peer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  sensor_data,       3)
#define ai_edgez_halow_Peer_CALLBACK NULL
#define ai_edgez_halow_Peer_DEFAULT NULL
#define ai_edgez_halow_Peer_sensor_data_MSGTYPE ai_edgez_halow_SensorData

#define ai_edgez_halow_Beacon_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   user_id_high,      1) \
X(a, STATIC,   SINGULAR, UINT64,   user_id_low,       2) \
X(a, STATIC,   SINGULAR, STRING,   user_name,         3) \
X(a, STATIC,   SINGULAR, BYTES,    user_public_key,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,          5) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,         6) \
X(a, STATIC,   SINGULAR, UENUM,    marker,            7) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,       8) \
X(a, STATIC,   SINGULAR, UINT32,   channel_number,    9) \
X(a, STATIC,   SINGULAR, BOOL,     sleeping,         10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  geo_fence,       100) \
X(a, STATIC,   REPEATED, MESSAGE,  sensor_data,     101)
#define ai_edgez_halow_Beacon_CALLBACK NULL
#define ai_edgez_halow_Beacon_DEFAULT NULL
#define ai_edgez_halow_Beacon_geo_fence_MSGTYPE ai_edgez_halow_GeoFence
#define ai_edgez_halow_Beacon_sensor_data_MSGTYPE ai_edgez_halow_SensorData

#define ai_edgez_halow_HaLowInterfaceStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     supported,         1) \
X(a, STATIC,   SINGULAR, BOOL,     stack_initialized,   2) \
X(a, STATIC,   SINGULAR, BOOL,     mesh_mode,         3) \
X(a, STATIC,   SINGULAR, BOOL,     link_up,           4) \
X(a, STATIC,   SINGULAR, BOOL,     route_ready,       5) \
X(a, STATIC,   SINGULAR, BOOL,     ready_for_report,   6) \
X(a, STATIC,   SINGULAR, UINT32,   ethertype,         7) \
X(a, STATIC,   SINGULAR, STRING,   mesh_id,           8) \
X(a, STATIC,   SINGULAR, STRING,   ip_addr,           9) \
X(a, STATIC,   SINGULAR, STRING,   gateway,          10) \
X(a, STATIC,   SINGULAR, UINT64,   mac_address,      11) \
X(a, STATIC,   SINGULAR, UENUM,    license_status,   12) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,  13)
#define ai_edgez_halow_HaLowInterfaceStatus_CALLBACK NULL
#define ai_edgez_halow_HaLowInterfaceStatus_DEFAULT NULL

#define ai_edgez_halow_HaLowInitConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   country_code,      1) \
X(a, STATIC,   SINGULAR, STRING,   mesh_id,           2) \
X(a, STATIC,   SINGULAR, STRING,   passphrase,        3) \
X(a, STATIC,   SINGULAR, UINT32,   max_hop,           4) \
X(a, STATIC,   SINGULAR, UINT64,   user_id_high,      5) \
X(a, STATIC,   SINGULAR, UINT64,   user_id_low,       6) \
X(a, STATIC,   SINGULAR, STRING,   user_name,         7) \
X(a, STATIC,   SINGULAR, BYTES,    user_public_key,   8) \
X(a, STATIC,   SINGULAR, STRING,   marker,            9) \
X(a, STATIC,   SINGULAR, BOOL,     has_location,     10) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,         11) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,        12) \
X(a, STATIC,   SINGULAR, UINT32,   mesh_bandwidth_mhz,  13) \
X(a, STATIC,   SINGULAR, UINT32,   mesh_frequency_khz,  14)
#define ai_edgez_halow_HaLowInitConfig_CALLBACK NULL
#define ai_edgez_halow_HaLowInitConfig_DEFAULT NULL

#define ai_edgez_halow_DeviceSettings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   SINGULAR, BOOL,     device_mode_enabled,   2) \
X(a, STATIC,   SINGULAR, STRING,   mesh_id,           3) \
X(a, STATIC,   SINGULAR, BOOL,     share_location,    4) \
X(a, STATIC,   SINGULAR, STRING,   user_name,         5) \
X(a, STATIC,   SINGULAR, UENUM,    marker,            6) \
X(a, STATIC,   SINGULAR, UINT32,   beacon_interval_seconds,   7) \
X(a, STATIC,   SINGULAR, UINT64,   user_id_high,      8) \
X(a, STATIC,   SINGULAR, UINT64,   user_id_low,       9) \
X(a, STATIC,   SINGULAR, BYTES,    user_public_key,  10) \
X(a, STATIC,   SINGULAR, BYTES,    user_private_key,  11) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,         12) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,        13) \
X(a, STATIC,   SINGULAR, UINT32,   max_hop,          14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  geo_fence,        15) \
X(a, STATIC,   SINGULAR, STRING,   uart_i2c_sensor_type,  16) \
X(a, STATIC,   SINGULAR, STRING,   rs485_sensor_type,  17) \
X(a, STATIC,   SINGULAR, UINT32,   geo_index,        18) \
X(a, STATIC,   SINGULAR, STRING,   passphrase,       19) \
X(a, STATIC,   SINGULAR, STRING,   upstream_wifi_ssid,  20) \
X(a, STATIC,   SINGULAR, STRING,   upstream_wifi_passphrase,  21) \
X(a, STATIC,   SINGULAR, UINT64,   beacon_unicast,   22) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,      24) \
X(a, STATIC,   SINGULAR, BOOL,     sleep_mode_enabled,  25) \
X(a, STATIC,   SINGULAR, UINT32,   mesh_frequency_khz,  26) \
X(a, STATIC,   SINGULAR, UINT32,   mesh_bandwidth_mhz,  27) \
X(a, STATIC,   SINGULAR, BOOL,     device_gps_enabled,  28)
#define ai_edgez_halow_DeviceSettings_CALLBACK NULL
#define ai_edgez_halow_DeviceSettings_DEFAULT NULL
#define ai_edgez_halow_DeviceSettings_geo_fence_MSGTYPE ai_edgez_halow_GeoFence

#define ai_edgez_halow_ScriptConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   SINGULAR, UINT32,   script_id,         2) \
X(a, STATIC,   SINGULAR, STRING,   name,              3) \
X(a, STATIC,   SINGULAR, UINT32,   version,           4) \
X(a, STATIC,   SINGULAR, UINT32,   total_size,        5) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            6) \
X(a, STATIC,   SINGULAR, BYTES,    chunk,             7) \
X(a, STATIC,   SINGULAR, STRING,   sensor_type,       8) \
X(a, STATIC,   SINGULAR, BOOL,     select_uart_i2c,   9) \
X(a, STATIC,   SINGULAR, BOOL,     select_rs485,     10) \
X(a, STATIC,   SINGULAR, UINT32,   global_buffer_size,  11) \
X(a, STATIC,   SINGULAR, STRING,   mime_type,        12)
#define ai_edgez_halow_ScriptConfig_CALLBACK NULL
#define ai_edgez_halow_ScriptConfig_DEFAULT NULL

extern const pb_msgdesc_t ai_edgez_halow_MessageBody_msg;
extern const pb_msgdesc_t ai_edgez_halow_Report_msg;
extern const pb_msgdesc_t ai_edgez_halow_NetworkPacket_msg;
extern const pb_msgdesc_t ai_edgez_halow_GeoFence_msg;
extern const pb_msgdesc_t ai_edgez_halow_SensorData_msg;
extern const pb_msgdesc_t ai_edgez_halow_Peer_msg;
extern const pb_msgdesc_t ai_edgez_halow_Beacon_msg;
extern const pb_msgdesc_t ai_edgez_halow_HaLowInterfaceStatus_msg;
extern const pb_msgdesc_t ai_edgez_halow_HaLowInitConfig_msg;
extern const pb_msgdesc_t ai_edgez_halow_DeviceSettings_msg;
extern const pb_msgdesc_t ai_edgez_halow_ScriptConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ai_edgez_halow_MessageBody_fields &ai_edgez_halow_MessageBody_msg
#define ai_edgez_halow_Report_fields &ai_edgez_halow_Report_msg
#define ai_edgez_halow_NetworkPacket_fields &ai_edgez_halow_NetworkPacket_msg
#define ai_edgez_halow_GeoFence_fields &ai_edgez_halow_GeoFence_msg
#define ai_edgez_halow_SensorData_fields &ai_edgez_halow_SensorData_msg
#define ai_edgez_halow_Peer_fields &ai_edgez_halow_Peer_msg
#define ai_edgez_halow_Beacon_fields &ai_edgez_halow_Beacon_msg
#define ai_edgez_halow_HaLowInterfaceStatus_fields &ai_edgez_halow_HaLowInterfaceStatus_msg
#define ai_edgez_halow_HaLowInitConfig_fields &ai_edgez_halow_HaLowInitConfig_msg
#define ai_edgez_halow_DeviceSettings_fields &ai_edgez_halow_DeviceSettings_msg
#define ai_edgez_halow_ScriptConfig_fields &ai_edgez_halow_ScriptConfig_msg

/* Maximum encoded size of messages (where known) */
#define AI_EDGEZ_HALOW_USB_CONTROL_PB_H_MAX_SIZE ai_edgez_halow_NetworkPacket_size
#define ai_edgez_halow_Beacon_size               322
#define ai_edgez_halow_DeviceSettings_size       601
#define ai_edgez_halow_GeoFence_size             98
#define ai_edgez_halow_HaLowInitConfig_size      274
#define ai_edgez_halow_HaLowInterfaceStatus_size 133
#define ai_edgez_halow_MessageBody_size          475
#define ai_edgez_halow_NetworkPacket_size        631
#define ai_edgez_halow_Peer_size                 87
#define ai_edgez_halow_Report_size               534
#define ai_edgez_halow_ScriptConfig_size         425
#define ai_edgez_halow_SensorData_size           8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
