/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "usb_control.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ai_edgez_halow_MessageBody, ai_edgez_halow_MessageBody, 2)


PB_BIND(ai_edgez_halow_Report, ai_edgez_halow_Report, 2)


PB_BIND(ai_edgez_halow_NetworkPacket, ai_edgez_halow_NetworkPacket, 2)


PB_BIND(ai_edgez_halow_GeoFence, ai_edgez_halow_GeoFence, AUTO)


PB_BIND(ai_edgez_halow_SensorData, ai_edgez_halow_SensorData, AUTO)


PB_BIND(ai_edgez_halow_Peer, ai_edgez_halow_Peer, AUTO)


PB_BIND(ai_edgez_halow_Beacon, ai_edgez_halow_Beacon, 2)


PB_BIND(ai_edgez_halow_HaLowInterfaceStatus, ai_edgez_halow_HaLowInterfaceStatus, AUTO)


PB_BIND(ai_edgez_halow_HaLowInitConfig, ai_edgez_halow_HaLowInitConfig, 2)


PB_BIND(ai_edgez_halow_DeviceSettings, ai_edgez_halow_DeviceSettings, 2)


PB_BIND(ai_edgez_halow_ScriptConfig, ai_edgez_halow_ScriptConfig, 2)
